# Generated by Django 4.2.6 on 2023-10-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0006_delete_videoproxy_videoallproxy_videopublishedproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft')], default='DR', max_length=2)),
                ('videos', models.ManyToManyField(blank=True, to='videos.video')),
            ],
        ),
    ]
